"""empty message

Revision ID:d056c6a37bba
Revises: 9a15f4b1a6e1
Create Date: 2023-06-21 09:56:47.839913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd056c6a37bba'
down_revision = '9a15f4b1a6e1'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users' , sa.Column('email', sa.String() , nullable= False))
    op.create_unique_constraint("email", 'users', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None , 'users' , type_='unique')
    op.drop_column('users', 'email')

    # ### end Alembic commands ###
